import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import '@papyrs/stylo';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Stylo + Next.js</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/*@ts-ignore*/}
      <stylo-editor>
        <article contentEditable="true">
          <h1>Stylo + Next.js</h1>
          <p>SSR is working</p>
          <hr />
          <ul>
            <li>Hello</li>
            <li>Stylo</li>
            <li>and</li>
            <li>Next.js</li>
          </ul>
          <p>드래그 하시면 툴바가 열립니다.</p>
        </article>
        {/*@ts-ignore*/}
      </stylo-editor>
    </div>
  );
};

export default Home;
